### ISSUE TITLE
Build passing on Travis CI and add badge to Readme

### ISSUE THREAD

**Issue by pwab** [pwab/godot-search#5]
**Todo**

- [x] Build passed on python 2.x
- [x] Build passed on python 3.x
- [x] Added badge to Readme file
